config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'public#welcome'
  get :about, to: 'public#about'
  get :contact_us, to: 'public#contact_us'

  resource :public, only: [], controller: 'public' do
    post :create_contact_form_info
  end

  resource :dashboard, only: [:show], controller: 'dashboard'
  resources :users, only: %I[show index] do
    member do
      get :follow
      delete :un_follow
    end
    resources :articles, only: %I[show index]
  end
  namespace :me do
    resources :articles
    resource :users
  end

  resources :articles, only: %I[show index] do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
# frozen_string_literal: true

# articles model
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :history

  belongs_to :user, inverse_of: :articles
  has_many :comments, dependent: :destroy, inverse_of: :article

  validates :title, :content, presence: true
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# article controller for general user
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.friendly.find(params[:id])
    return unless current_user

    @comment = @article.comments.new(user: current_user)
  end
end

app/controllers/me/articles_controller.rb
# frozen_string_literal: true

# me module
module Me
  # current user articles
  class ArticlesController < ApplicationController
    layout 'dashboard'
    before_action :authenticate_user!
    before_action :scope
    before_action :find_article, only: %I[edit update show destroy]

    def index
      @articles = scope
    end

    def show; end

    def new
      @article = scope.new
    end

    def edit; end

    def create
      @article = scope.new(article_params)

      if @article.save
        ArticleMailer.with(article: @article, user: current_user).new_article.deliver_later
        redirect_to me_article_path(@article)
      else
        render 'new'
      end
    end

    def update
      if @article.update(article_params)
        redirect_to me_article_path(@article)
      else
        render 'edit'
      end
    end

    def destroy
      @article.destroy
      redirect_to me_articles_path
    end

    private

    def scope
      @scope ||= current_user.articles
    end

    def find_article
      @article = scope.friendly.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :user_id)
    end
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

# Articles view helper
module ArticlesHelper
  def author_name(article)
    article.user.full_name.presence || article.user.email
  end
end

app/helpers/users/articles_helper.rb
# frozen_string_literal: true

# users module
module Users
  # for artilces view helper
  module ArticlesHelper
  end
end

app/views/articles/_comment.html.erb
<div class='border p-2 mb-1 d-flex justify-content-between' id= 'comment_<%= comment.slug %>' >
    <span>
        <b>
        <%= comment.user&.full_name || "User" %>
        </b>
    <p class='mb-0 ps-3'><%= comment.content %></p>
    </span>
    <span>
        <% if current_user %>
            <%= link_to 'reply', new_article_comment_path(article_id: @article.slug, comment_id: comment.slug), remote: true %>
            <% if comment.user == current_user %>
                <%= link_to 'edit', "#" %>
                <%= link_to 'delete', article_comment_path(@article, comment), method: :delete,  data: {confirm: "Are you sure?"} %>
            <% end %>
        <% end %>
    </span>
</div>

app/views/articles/_comments.html.erb
<% @article.comments.each do |comment| %>
    <% next unless comment.content %>
    <%= render 'comment', comment: comment %>
<% end %>

app/views/articles/_new_comment.html.erb
<%= form_with model: [ @article, @comment ] do |f|%>
    <%= f.hidden_field :parent_id if @comment.parent_id %>

    <div class="form-group row mb-2">
        <div class='col-md-11'>
            <%= f.text_field :content, class: 'form-control', placeholder: 'Enter Content' %>
        </div>
        <div class='col-md-1'>
            <%= f.submit 'Submit', class: 'w-20' %>
        </div>
    </div>
<%end%>

app/views/articles/index.html.erb
<div class="container mt-5">

<h1>All Articles</h1>

    <div class="row">
        <% @articles.each do |article| %>
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="https://via.placeholder.com/300" class="card-img-top" alt="Article Image">
                    <div class="card-body">
                    <h5 class="card-title"><%= article.title %></h5>
                    <p class="card-text">Auther: <%= link_to author_name(article), user_path(article.user.slug) %></p>
                    <p class="card-text"><%= article.content.truncate(60)%></p>
                    <%= link_to 'Read More', article_path(article), class: 'btn btn-primary' %>
                    </div>
                </div>
            </div>
        <% end %>   
    </div>
</div>

app/views/articles/show.html.erb
<div class='container'>
    <div class='text-center mt-3'>
        <h2><%= @article.title %></h2>
        <p>
            Author: <%= @article.user.full_name %>
        </p>
        <p>
            Published: <%= @article.created_at %>
        </p>
    </div>
    <hr/>
    <p>
        <%= @article.content %>
    </p>
    <hr/>
    <h3>Comments</h3>
        <%= render 'new_comment' if current_user %>
        <div id='article_comments'>
            <%= render 'comments' %>
        </div>
    <div>
    </div>
</div>