config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'public#welcome'
  get :about, to: 'public#about'
  get :contact_us, to: 'public#contact_us'

  resource :public, only: [], controller: 'public' do
    post :create_contact_form_info
  end

  resource :dashboard, only: [:show], controller: 'dashboard'
  resources :users, only: %I[show index] do
    member do
      get :follow
      delete :un_follow
    end
    resources :articles, only: %I[show index]
  end
  namespace :me do
    resources :articles
    resource :users
  end

  resources :articles, only: %I[show index] do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

# users model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :slug_candidate, use: :history
  acts_as_followable
  acts_as_follower

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: [:google_oauth2]
  has_many :articles, dependent: :destroy, inverse_of: :user
  has_many :comments, dependent: :destroy, inverse_of: :user

  validates :first_name, :last_name, :email, presence: true

  def full_name
    return '' unless first_name && last_name

    "#{first_name} #{last_name}"
  end

  def slug_candidate
    ["#titan-#{full_name}"]
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(first_name: data['first_name'],
                         last_name: data['last_name'],
                         email: data['email'],
                         password: Devise.friendly_token[0, 20])
    user
  end
end

app/controllers/me/users_controller.rb
# frozen_string_literal: true

module Me
  # users controller
  class UsersController < ApplicationController
    before_action :set_user, only: %I[edit update]
    def edit; end

    def update
      if current_user.update(user_params)
        flash[:success] = 'User Updated successfully'
      else
        flash[:error] = 'Something Wrong!!'
      end
      redirect_back fallback_location: root_path
    end

    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end

    def set_user
      @user = current_user
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  # app/controllers/users/omniauth_callbacks_controller.rb:
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    before_action :set_user, only: [:google_oauth2]

    def google_oauth2
      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
    end

    private

    def set_user
      @user = User.from_omniauth(request.env['omniauth.auth'])
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# users controller for public users to show user profile and listing
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %I[follow un_follow]
  before_action :find_user, only: %I[show follow un_follow]

  def index
    @users = current_user ? User.where.not(id: current_user.id) : User.all
  end

  def show; end

  def follow
    current_user.follow(@user)
  end

  def un_follow
    current_user.stop_following(@user)
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/me/users_helper.rb
# frozen_string_literal: true

module Me
  # user helper
  module UsersHelper
  end
end

app/helpers/users/articles_helper.rb
# frozen_string_literal: true

# users module
module Users
  # for artilces view helper
  module ArticlesHelper
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# users helper
module UsersHelper
end

app/views/users/_follow_unfollow.html.erb
<% if current_user.following?(user) %>
    <%= link_to "un follow", un_follow_user_path(user), remote: true, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-secondary btn-sm' %>
<% else %>
    <%= link_to "follow", follow_user_path(user), remote: true, class: 'btn btn-secondary btn-small btn-sm' %>
<% end %>

app/views/users/follow.js.erb
$("#user_<%= @user.slug %>").html("<%= escape_javascript(render 'follow_unfollow', user: @user) %>")

app/views/users/index.html.erb
<div class="container mt-5">

<h1>All Authers</h1>

    <div class="row">
        <% @users.each do |user| %>
            <!-- Sample Article Card (Repeat this block for each article) -->
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="https://via.placeholder.com/300" class="card-img-top" alt="Article Image">
                    <div class="card-body">
                    <h5 class="card-title"><%= user.full_name.titleize %></h5>
                    <p class="card-text">Software Engineer</p>
                    <div>
                        <%= link_to 'Profile', user_path(user), class: 'btn btn-primary btn-sm' %>
                        <% if current_user %>
                            <span id="user_<%= user.slug %>">
                                <%= render 'follow_unfollow', user: user %>
                            </span>
                        <% end %>
                    </div>
                    </div>
                </div>
            </div>

            <!-- Repeat the above card block for each article in your collection -->
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class='container'>
    <div class="border w-100 mb-5">
        <h1 class='ml-3'><%= @user.full_name.titleize %></h1>
    </div>
    <ul>
        <% @user.articles.each_with_index do |article| %>
            <li>
            <%= link_to article_path(article) do %>
                <h4>
                    <%= article.title %>
                </h4>
            <% end %>
            </li>
        <% end %>
    </ul>
</div>

app/views/users/un_follow.js.erb
$("#user_<%= @user.slug %>").html("<%= escape_javascript(render 'follow_unfollow', user: @user) %>")