config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'public#welcome'
  get :about, to: 'public#about'
  get :contact_us, to: 'public#contact_us'

  resource :public, only: [], controller: 'public' do
    post :create_contact_form_info
  end

  resource :dashboard, only: [:show], controller: 'dashboard'
  resources :users, only: %I[show index] do
    member do
      get :follow
      delete :un_follow
    end
    resources :articles, only: %I[show index]
  end
  namespace :me do
    resources :articles
    resource :users
  end

  resources :articles, only: %I[show index] do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
# frozen_string_literal: true

# articles model
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :history

  belongs_to :user, inverse_of: :articles
  has_many :comments, dependent: :destroy, inverse_of: :article

  validates :title, :content, presence: true
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# article controller for general user
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.friendly.find(params[:id])
    return unless current_user

    @comment = @article.comments.new(user: current_user)
  end
end

app/controllers/me/articles_controller.rb
# frozen_string_literal: true

# me module
module Me
  # current user articles
  class ArticlesController < ApplicationController
    layout 'dashboard'
    before_action :authenticate_user!
    before_action :scope
    before_action :find_article, only: %I[edit update show destroy]

    def index
      @articles = scope
    end

    def show; end

    def new
      @article = scope.new
    end

    def edit; end

    def create
      @article = scope.new(article_params)

      if @article.save
        ArticleMailer.with(article: @article, user: current_user).new_article.deliver_later
        redirect_to me_article_path(@article)
      else
        render 'new'
      end
    end

    def update
      if @article.update(article_params)
        redirect_to me_article_path(@article)
      else
        render 'edit'
      end
    end

    def destroy
      @article.destroy
      redirect_to me_articles_path
    end

    private

    def scope
      @scope ||= current_user.articles
    end

    def find_article
      @article = scope.friendly.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :user_id)
    end
  end
end

app/controllers/me/users_controller.rb
# frozen_string_literal: true

module Me
  # users controller
  class UsersController < ApplicationController
    before_action :set_user, only: %I[edit update]
    def edit; end

    def update
      if current_user.update(user_params)
        flash[:success] = 'User Updated successfully'
      else
        flash[:error] = 'Something Wrong!!'
      end
      redirect_back fallback_location: root_path
    end

    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end

    def set_user
      @user = current_user
    end
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

# Articles view helper
module ArticlesHelper
  def author_name(article)
    article.user.full_name.presence || article.user.email
  end
end

app/helpers/me/users_helper.rb
# frozen_string_literal: true

module Me
  # user helper
  module UsersHelper
  end
end

app/helpers/users/articles_helper.rb
# frozen_string_literal: true

# users module
module Users
  # for artilces view helper
  module ArticlesHelper
  end
end

app/views/me/articles/_form.html.erb
<%= render "layouts/dashboard_content_header", title: 'Articles' %>

<%= form_with model: [:me, @article], local: true do |f|%>
  <div class="form-group row mb-2">
    <%= f.label :title, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter Title' %>
    </div>
  </div>
  <div class="form-group row mb-2">
    <%= f.label :content, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
        <%= f.text_area :content, class: 'form-control', placeholder: 'Enter Content' %>
    </div>
  </div>
    <div class="form-group mb-2 text-center">
        <%= f.submit 'Submit', class: 'w-20' %>
    </div>
<%end%>

app/views/me/articles/index.html.erb
<%= render "layouts/dashboard_content_header", title: 'Articles' %>
<%= link_to 'Add Article', new_me_article_path, class: 'btn btn-primary' %>
<div class="table-responsive small">
<table class="table table-striped table-sm">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Content</th>
        <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @articles.each_with_index do |article, index| %>
        <tr>
            <td><%= index + 1 %></td>
            <td><%= article.title %></td>
            <td><%= article.content.truncate(125) %></td>
            <td>
                <%= link_to "show", me_article_path(article) %>
                <%= link_to "edit", edit_me_article_path(article) %>
                <%= link_to "delete", me_article_path(article), method: :delete, data: {confirm: "Are you sure?"} %>
            </td>
        </tr>
    <% end %>
    </tbody>
</table>
</div>

app/views/me/articles/new.html.erb
<%= render "layouts/dashboard_content_header", title: 'Articles' %>

<%= form_with model: [:me, @article], local: true do |f|%>
  <div class="form-group row mb-2">
    <%= f.label :title, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter Title' %>
    </div>
  </div>
  <div class="form-group row mb-2">
    <%= f.label :content, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
        <%= f.text_area :content, class: 'form-control', size: "colsxrols", placeholder: 'Enter Content' %>
    </div>
  </div>
    <div class="form-group mb-2 text-center">
        <%= f.submit 'Submit', class: 'w-20' %>
    </div>
<%end%>

app/views/me/articles/show.html.erb
<%= render "layouts/dashboard_content_header", title: 'Articles' %>

<div class='p-3'>
    <h2><%= @article.title %></h2>
    <hr />
    <p><%= @article.content %></p>
</div>