config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'public#welcome'
  get :about, to: 'public#about'
  get :contact_us, to: 'public#contact_us'

  resource :public, only: [], controller: 'public' do
    post :create_contact_form_info
  end

  resource :dashboard, only: [:show], controller: 'dashboard'
  resources :users, only: %I[show index] do
    member do
      get :follow
      delete :un_follow
    end
    resources :articles, only: %I[show index]
  end
  namespace :me do
    resources :articles
    resource :users
  end

  resources :articles, only: %I[show index] do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

# application record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# articles model
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :history

  belongs_to :user, inverse_of: :articles
  has_many :comments, dependent: :destroy, inverse_of: :article

  validates :title, :content, presence: true
end

app/models/comment.rb
# frozen_string_literal: true

# comments model
class Comment < ApplicationRecord
  extend FriendlyId
  friendly_id :comment_slug, use: :history

  belongs_to :article
  belongs_to :user
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy, inverse_of: :comment
  belongs_to :parent, class_name: 'Comment', optional: true

  validates :content, presence: true

  private

  def comment_slug
    "#{content&.first(5)}_comment"
  end
end

app/models/contact_form_info.rb
# frozen_string_literal: true

class ContactFormInfo < ApplicationRecord
end

app/models/follow.rb
# frozen_string_literal: true

# follow and unfollow model
class Follow < ApplicationRecord
  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    update(:blocked, true)
  end
end

app/models/user.rb
# frozen_string_literal: true

# users model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :slug_candidate, use: :history
  acts_as_followable
  acts_as_follower

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: [:google_oauth2]
  has_many :articles, dependent: :destroy, inverse_of: :user
  has_many :comments, dependent: :destroy, inverse_of: :user

  validates :first_name, :last_name, :email, presence: true

  def full_name
    return '' unless first_name && last_name

    "#{first_name} #{last_name}"
  end

  def slug_candidate
    ["#titan-#{full_name}"]
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(first_name: data['first_name'],
                         last_name: data['last_name'],
                         email: data['email'],
                         password: Devise.friendly_token[0, 20])
    user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# application controller
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# article controller for general user
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.friendly.find(params[:id])
    return unless current_user

    @comment = @article.comments.new(user: current_user)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# comments controller
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :article

  def new
    @comment = @article.comments.new(parent: comment)
  end

  def edit
    @comment = Comment.find(params[:id])
    authorize @post, :update?
  end

  def create
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def update
    @comment = Comment.find(params[:id])
    authorize @post
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    authorize @post
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :article_id, :parent_id)
  end

  def article
    @article ||= Article.friendly.find(params[:article_id])
  end

  def comment
    @comment ||= @article.comments.friendly.find(params[:comment_id])
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# Dashboard for user
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def show; end
end

app/controllers/public_controller.rb
# frozen_string_literal: true

# public controller to show public pages
class PublicController < ApplicationController
  def welcome
    @artilces = Article.all
  end

  def about; end

  def contact_us
    @contact_form_info = ContactFormInfo.new
  end

  def create_contact_form_info
    @contact_form_info = ContactFormInfo.new(contact_form_info_params)
    if @contact_form_info.save
      redirect_to root_path
    else
      render 'contact_us'
    end
  end

  private

  def contact_form_info_params
    params.require(:contact_form_info).permit(:first_name, :last_name, :email, :content)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# users controller for public users to show user profile and listing
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %I[follow un_follow]
  before_action :find_user, only: %I[show follow un_follow]

  def index
    @users = current_user ? User.where.not(id: current_user.id) : User.all
  end

  def show; end

  def follow
    current_user.follow(@user)
  end

  def un_follow
    current_user.stop_following(@user)
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# appiciton helper
module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

# Articles view helper
module ArticlesHelper
  def author_name(article)
    article.user.full_name.presence || article.user.email
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# comments view helper
module CommentsHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

# for dashbord helper methods
module DashboardHelper
end

app/helpers/me/users_helper.rb
# frozen_string_literal: true

module Me
  # user helper
  module UsersHelper
  end
end

app/helpers/public_helper.rb
# frozen_string_literal: true

# for public pages view helpers
module PublicHelper
end

app/helpers/users/articles_helper.rb
# frozen_string_literal: true

# users module
module Users
  # for artilces view helper
  module ArticlesHelper
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# users helper
module UsersHelper
end

app/views/layouts/_dashboard_content_header.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"><%= title %></h1>
</div>

app/views/layouts/_dashboard_sidebar.html.erb
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
    <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="sidebarMenuLabel">Rails Titans</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
        <ul class="nav flex-column">
        <li class="nav-item">
            <%= link_to dashboard_path, class: 'nav-link d-flex align-items-center gap-2 active', 'aria-current': 'page' do %>
                <svg class="bi"><use xlink:href="#house-fill"></use></svg>
                Dashboard
            <% end %>
        </li>
        <li class="nav-item">
            <%= link_to me_articles_path, class: 'nav-link d-flex align-items-center gap-2 active', 'aria-current': 'page' do %>
                <svg class="bi"><use xlink:href="#file-earmark"></use></svg>
                Articles
            <% end %>
        </li>
        <li class="nav-item">
            <%= link_to edit_me_users_path, class: 'nav-link d-flex align-items-center gap-2 active', 'aria-current': 'page' do %>
                <svg class="bi"><use xlink:href="#file-earmark"></use></svg>
                Profile
            <% end %>
        </li>
        </ul>
    </div>
    </div>
</div>

app/views/layouts/_public_navbar.html.erb
<div class="container-fluid">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-2 border-bottom">
      <div class="col-md-3 mb-2 mb-md-0">
        <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
          Rails Titans
        </a>
      </div>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li>
          <%= link_to "Home", root_path, class: 'nav-link px-2 link-secondary' %>
        </li>
        <li>
          <%= link_to "Articles", articles_path, class: 'nav-link px-2' %>
        </li>
        <li>
          <%= link_to "Authors", users_path, class: 'nav-link px-2' %>
        </li>
        <li>
          <%= link_to "Contact Us", contact_us_path, class: 'nav-link px-2' %>
        </li>
        <li>
          <%= link_to "About", about_path, class: 'nav-link px-2' %>
        </li>
      </ul>
       <div class="col-md-3 text-end">
      <% if current_user %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary me-2" %>
          <%= link_to "Dashboard", dashboard_path, class: 'btn btn-primary' %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: 'btn btn-outline-primary me-2' %>
        <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-primary' %>
      <% end %>
      </div>
    </header>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTitans</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/public_navbar' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTitans</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/public_navbar' %>
    <div class="container-fluid">
        <div class="row">
            <%= render "layouts/dashboard_sidebar" %>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <%= yield %>
            </main>
        </div>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>